/* ============================================================
   THANH LAM — PORTFOLIO DATA
   19 projects · MARKETING CASE STUDY / CREATIVE WORK
   `title_vi` holds the Vietnamese title; other translated fields
   (category, subCategory, tags, origin) are resolved via shared
   maps in js/i18n.js so they stay consistent across projects.
   ============================================================ */

window.PROJECTS = [
  {
    num: 1,
    title: "Korean Skincare Brand",
    title_vi: "Thương hiệu mỹ phẩm Hàn Quốc",
    origin: "Lubylab",
    category: "MARKETING CASE STUDY",
    subCategory: "Marketing Lead",
    date: "2026",
    slug: "lubylab-1",
    tags: ["Marketing Lead"],
    year: 2026,
    img: "assets/img/thumb/lubylab-1.webp",
    mobileImg: "assets/img/thumb/mobile/lubylab-1.jpg"
  },
  {
    num: 2,
    title: "Born In Red Shortfilm",
    title_vi: "Phim ngắn Born in Red",
    origin: "Campari Competition",
    category: "CREATIVE WORK",
    subCategory: "Story-telling, Photography",
    date: "2025",
    slug: "campari-competition",
    tags: ["Story-telling", "Photography"],
    year: 2025,
    img: "assets/img/thumb/campari-competition.webp"
  },
  {
    num: 3,
    title: "Wellness Spa",
    title_vi: "Thương hiệu spa chăm sóc sức khỏe",
    origin: "Fae Beauty",
    category: "MARKETING CASE STUDY",
    subCategory: "Brand Designer",
    date: "2025",
    slug: "fae-beauty",
    tags: ["Brand Designer"],
    year: 2025,
    img: "assets/img/thumb/fae-beauty.webp",
    mobileImg: "assets/img/thumb/mobile/fae-beauty.jpg"
  },
  {
    num: 4,
    title: "Year Of Snake - Lucky Money",
    title_vi: "Tết Ất Tỵ — Bao lì xì",
    origin: "New Year 2025",
    category: "CREATIVE WORK",
    subCategory: "Packaging, Merchandise",
    date: "2025",
    slug: "new-year-2025",
    tags: ["Packaging", "Merchandise"],
    year: 2025,
    img: "assets/img/thumb/new-year-2025.webp"
  },
  {
    num: 5,
    title: "Formulation For Family Care",
    title_vi: "Dòng sản phẩm chăm sóc gia đình",
    origin: "Celavie",
    category: "MARKETING CASE STUDY",
    archiveOnly: true,
    subCategory: "Branding, Packaging",
    date: "2024",
    slug: "celavie",
    tags: ["Branding", "Packaging"],
    year: 2024,
    img: "assets/img/thumb/celavie.webp"
  },
  {
    num: 6,
    title: "Xmas Merchandise",
    title_vi: "Bộ vật phẩm Giáng sinh",
    origin: "Merit Christmas",
    category: "CREATIVE WORK",
    subCategory: "Illustration, Merch",
    date: "2024",
    slug: "merit-christmas",
    tags: ["Illustration", "Merch"],
    year: 2024,
    img: "assets/img/thumb/merit-christmas.webp"
  },
  {
    num: 7,
    title: "Hotel Of Serenity",
    title_vi: "Khách sạn an yên",
    origin: "Mandala Hotel",
    category: "MARKETING CASE STUDY",
    subCategory: "Customer Relations Management",
    date: "2023",
    slug: "mandala-hotel",
    tags: ["Customer Relations Management"],
    year: 2023,
    img: "assets/img/thumb/mandala-hotel.webp",
    mobileImg: "assets/img/thumb/mobile/mandala-hotel.jpg"
  },
  {
    num: 8,
    title: "Thailand Skincare Exhibition",
    title_vi: "Triển lãm mỹ phẩm tại Thái Lan",
    origin: "Lubylab",
    category: "MARKETING CASE STUDY",
    subCategory: "Booth Design, B2B Communication",
    date: "2026",
    slug: "lubylab-2",
    tags: ["Booth Design", "B2B Communication"],
    year: 2026,
    img: "assets/img/thumb/lubylab-2.webp",
    mobileImg: "assets/img/thumb/mobile/lubylab-2.jpg"
  },
  {
    num: 9,
    title: "Color Changing Clothing",
    title_vi: "Thời trang biến đổi màu sắc",
    origin: "Chromatic",
    category: "CREATIVE WORK",
    archiveOnly: true,
    subCategory: "Logo, Mockup",
    date: "2024",
    slug: "chromatic",
    tags: ["Logo", "Mockup"],
    year: 2024,
    img: "assets/img/9.webp"
  },
  {
    num: 10,
    title: "Eco-Friendly Wear",
    title_vi: "Thời trang thân thiện với môi trường",
    origin: "Leger-Boo",
    category: "CREATIVE WORK",
    subCategory: "Social, Logo",
    date: "2024",
    slug: "leger-boo",
    tags: ["Social", "Logo"],
    year: 2024,
    img: "assets/img/thumb/leger-boo.webp"
  },
  {
    num: 11,
    title: "Environment Solution Pioneer",
    title_vi: "Tiên phong giải pháp môi trường",
    origin: "Biolotus",
    category: "MARKETING CASE STUDY",
    subCategory: "Brand Marketing",
    date: "2025",
    slug: "biolotus",
    tags: ["Brand Marketing"],
    year: 2025,
    img: "assets/img/thumb/biolotus.webp",
    mobileImg: "assets/img/thumb/mobile/biolotus.jpg"
  },
  {
    num: 12,
    title: "Post-Apocalypse Theatre Experience",
    title_vi: "Trải nghiệm sân khấu hậu tận thế",
    origin: "Dionysus",
    category: "CREATIVE WORK",
    archiveOnly: true,
    subCategory: "Stage Design, Social",
    date: "2023",
    slug: "dionysus",
    tags: ["Stage Design", "Social"],
    year: 2023,
    img: "assets/img/12.webp"
  },
  {
    num: 13,
    title: "Fine Prints",
    title_vi: "Ấn phẩm nghệ thuật",
    origin: "Poster Design",
    category: "CREATIVE WORK",
    archiveOnly: true,
    subCategory: "Art, Photograph",
    date: "2024",
    slug: "poster-design",
    tags: ["Art", "Photograph"],
    year: 2024,
    img: "assets/img/13.webp"
  },
  {
    num: 14,
    title: "Product Development",
    title_vi: "Phát triển sản phẩm",
    origin: "Lubylab",
    category: "MARKETING CASE STUDY",
    subCategory: "Product Development, Design",
    date: "2026",
    slug: "lubylab-3",
    tags: ["Product Development", "Design"],
    year: 2026,
    img: "assets/img/thumb/lubylab-3.webp",
    mobileImg: "assets/img/thumb/mobile/lubylab-3.jpg"
  },
  {
    num: 15,
    title: "Ideas Worth Spreading",
    title_vi: "Ý tưởng đáng lan tỏa",
    origin: "TEDxBUV",
    category: "MARKETING CASE STUDY",
    subCategory: "Web Builder, Social Media",
    date: "2023",
    slug: "tedxbuv",
    tags: ["Web Builder", "Social Media"],
    year: 2023,
    img: "assets/img/thumb/tedxbuv.webp",
    mobileImg: "assets/img/thumb/mobile/tedxbuv.jpg"
  },
  {
    num: 16,
    title: "Concept Photobook",
    title_vi: "Sách ảnh nghệ thuật ý niệm",
    origin: "Photograph",
    category: "CREATIVE WORK",
    subCategory: "Photography",
    date: "2025",
    slug: "photograph-1",
    tags: ["Photography"],
    year: 2025,
    img: "assets/img/thumb/photograph-1.webp"
  },
  {
    num: 17,
    title: "Personal Branding",
    title_vi: "Thương hiệu cá nhân",
    origin: "Thanh Lam",
    category: "CREATIVE WORK",
    archiveOnly: true,
    subCategory: "Identity",
    date: "2024",
    slug: "thanh-lam",
    tags: ["Identity"],
    year: 2024,
    img: "assets/img/17.webp"
  },
  {
    num: 18,
    title: "Couple Photobook",
    title_vi: "Sách ảnh cặp đôi",
    origin: "Photograph",
    category: "CREATIVE WORK",
    subCategory: "Photography",
    date: "2026",
    slug: "photograph-2",
    tags: ["Photography"],
    year: 2026,
    img: "assets/img/thumb/photograph-2.webp"
  },
  {
    num: 19,
    title: "Dimsum Corner",
    title_vi: "Dimsum Corner",
    origin: "Mandala Hotel",
    category: "MARKETING CASE STUDY",
    subCategory: "Brand Marketing, Illustration",
    date: "2023",
    slug: "dimsum-corner",
    tags: ["Brand Marketing", "Illustration"],
    year: 2023,
    img: "assets/img/thumb/dimsum-corner.webp",
    mobileImg: "assets/img/thumb/mobile/dimsum-corner.jpg"
  }
];

window.CATEGORIES = ["ALL", "MARKETING CASE STUDY", "CREATIVE WORK"];
