/* ============================================================
   THANH LAM — PORTFOLIO DATA
   18 projects · MARKETING CASE STUDY / CREATIVE WORK
   `title_vi` holds the Vietnamese title; other translated fields
   (category, subCategory, tags, origin) are resolved via shared
   maps in js/i18n.js so they stay consistent across projects.
   ============================================================ */

window.PROJECTS = [
  {
    num: 1,
    title: "Korean Skincare Brand",
    title_vi: "Thương hiệu dưỡng da Hàn Quốc",
    origin: "Lubylab",
    category: "MARKETING CASE STUDY",
    subCategory: "Branding, Social, UI UX",
    date: "2026",
    slug: "lubylab-1",
    tags: ["Branding", "Social", "UI UX"],
    year: 2026,
    img: "assets/img/thumb/lubylab-1.webp"
  },
  {
    num: 2,
    title: "Born In Red Shortfilm",
    title_vi: "Phim ngắn Born In Red",
    origin: "Campari Competition",
    category: "CREATIVE WORK",
    subCategory: "Story-telling, Photography",
    date: "2025",
    slug: "campari-competition",
    tags: ["Story-telling", "Photography"],
    year: 2025,
    img: "assets/img/thumb/campari-competition.webp"
  },
  {
    num: 3,
    title: "Wellness Spa",
    title_vi: "Spa chăm sóc sức khỏe",
    origin: "Fae Beauty",
    category: "MARKETING CASE STUDY",
    subCategory: "Branding, Social",
    date: "2025",
    slug: "fae-beauty",
    tags: ["Branding", "Social"],
    year: 2025,
    img: "assets/img/thumb/fae-beauty.webp"
  },
  {
    num: 4,
    title: "Year Of Snake - Lucky Money",
    title_vi: "Năm Rắn - Lì Xì",
    origin: "New Year 2025",
    category: "CREATIVE WORK",
    subCategory: "Packaging, Merchandise",
    date: "2025",
    slug: "new-year-2025",
    tags: ["Packaging", "Merchandise"],
    year: 2025,
    img: "assets/img/thumb/new-year-2025.webp"
  },
  {
    num: 5,
    title: "Formulation For Family Care",
    title_vi: "Công thức cho cả gia đình",
    origin: "Celavie",
    category: "MARKETING CASE STUDY",
    subCategory: "Branding, Packaging",
    date: "2024",
    slug: "celavie",
    tags: ["Branding", "Packaging"],
    year: 2024,
    img: "assets/img/thumb/celavie.webp"
  },
  {
    num: 6,
    title: "Xmas Merchandise",
    title_vi: "Merch Giáng Sinh",
    origin: "Merit Christmas",
    category: "CREATIVE WORK",
    subCategory: "Illustration, Merch",
    date: "2024",
    slug: "merit-christmas",
    tags: ["Illustration", "Merch"],
    year: 2024,
    img: "assets/img/thumb/merit-christmas.webp"
  },
  {
    num: 7,
    title: "Hotel Of Serenity",
    title_vi: "Khách sạn của sự an yên",
    origin: "Mandala Hotel",
    category: "MARKETING CASE STUDY",
    subCategory: "Prints, Illustration",
    date: "2023",
    slug: "mandala-hotel",
    tags: ["Prints", "Illustration"],
    year: 2023,
    img: "assets/img/thumb/mandala-hotel.webp"
  },
  {
    num: 8,
    title: "Thailand Skincare Exhibition",
    title_vi: "Triển lãm dưỡng da Thái Lan",
    origin: "Lubylab",
    category: "MARKETING CASE STUDY",
    subCategory: "3D, B2B Communicate",
    date: "2026",
    slug: "lubylab-2",
    tags: ["3D", "B2B Communicate"],
    year: 2026,
    img: "assets/img/thumb/lubylab-2.webp"
  },
  {
    num: 9,
    title: "Color Changing Clothing",
    title_vi: "Trang phục đổi màu",
    origin: "Chromatic",
    category: "CREATIVE WORK",
    archiveOnly: true,
    subCategory: "Logo, Mockup",
    date: "2024",
    slug: "chromatic",
    tags: ["Logo", "Mockup"],
    year: 2024,
    img: "assets/img/9.webp"
  },
  {
    num: 10,
    title: "Eco-Friendly Wear",
    title_vi: "Thời trang thân thiện môi trường",
    origin: "Leger-Boo",
    category: "CREATIVE WORK",
    subCategory: "Social, Logo",
    date: "2024",
    slug: "leger-boo",
    tags: ["Social", "Logo"],
    year: 2024,
    img: "assets/img/thumb/leger-boo.webp"
  },
  {
    num: 11,
    title: "Environment Solution Pioneer",
    title_vi: "Tiên phong giải pháp môi trường",
    origin: "Biolotus",
    category: "MARKETING CASE STUDY",
    subCategory: "Branding",
    date: "2025",
    slug: "biolotus",
    tags: ["Branding"],
    year: 2025,
    img: "assets/img/thumb/biolotus.webp"
  },
  {
    num: 12,
    title: "Post-Apocalypse Theatre Experience",
    title_vi: "Trải nghiệm sân khấu hậu tận thế",
    origin: "Dionysus",
    category: "CREATIVE WORK",
    archiveOnly: true,
    subCategory: "Stage Design, Social",
    date: "2023",
    slug: "dionysus",
    tags: ["Stage Design", "Social"],
    year: 2023,
    img: "assets/img/12.webp"
  },
  {
    num: 13,
    title: "Fine Prints",
    title_vi: "Ấn phẩm nghệ thuật",
    origin: "Poster Design",
    category: "CREATIVE WORK",
    archiveOnly: true,
    subCategory: "Art, Photograph",
    date: "2024",
    slug: "poster-design",
    tags: ["Art", "Photograph"],
    year: 2024,
    img: "assets/img/13.webp"
  },
  {
    num: 14,
    title: "Product Packaging",
    title_vi: "Bao bì sản phẩm",
    origin: "Lubylab",
    category: "CREATIVE WORK",
    subCategory: "Product Design",
    date: "2026",
    slug: "lubylab-3",
    tags: ["Product Design"],
    year: 2026,
    img: "assets/img/thumb/lubylab-3.webp"
  },
  {
    num: 15,
    title: "Ideas Worth Spreading",
    title_vi: "Ý tưởng đáng lan tỏa",
    origin: "TEDxBUV",
    category: "MARKETING CASE STUDY",
    subCategory: "Website, UI, Social",
    date: "2023",
    slug: "tedxbuv",
    tags: ["Website", "UI", "Social"],
    year: 2023,
    img: "assets/img/thumb/tedxbuv.webp"
  },
  {
    num: 16,
    title: "Concept Photobook",
    title_vi: "Photobook concept",
    origin: "Photograph",
    category: "CREATIVE WORK",
    subCategory: "Photography",
    date: "2025",
    slug: "photograph-1",
    tags: ["Photography"],
    year: 2025,
    img: "assets/img/thumb/photograph-1.webp"
  },
  {
    num: 17,
    title: "Personal Branding",
    title_vi: "Thương hiệu cá nhân",
    origin: "Thanh Lam",
    category: "CREATIVE WORK",
    archiveOnly: true,
    subCategory: "Identity",
    date: "2024",
    slug: "thanh-lam",
    tags: ["Identity"],
    year: 2024,
    img: "assets/img/17.webp"
  },
  {
    num: 18,
    title: "Couple Photobook",
    title_vi: "Photobook cặp đôi",
    origin: "Photograph",
    category: "CREATIVE WORK",
    subCategory: "Photography",
    date: "2026",
    slug: "photograph-2",
    tags: ["Photography"],
    year: 2026,
    img: "assets/img/thumb/photograph-2.webp"
  },
  {
    num: 19,
    title: "Dimsum Corner",
    title_vi: "Dimsum Corner",
    origin: "Mandala Hotel",
    category: "MARKETING CASE STUDY",
    subCategory: "Branding, Illustration",
    date: "2023",
    slug: "dimsum-corner",
    tags: ["Branding", "Illustration"],
    year: 2023,
    img: "assets/img/thumb/dimsum-corner.webp"
  }
];

window.CATEGORIES = ["ALL", "MARKETING CASE STUDY", "CREATIVE WORK"];
